matyunya/smelte

src/components/Tabs/Tabs.svelte

When items = [{ to: "/components", ...}, { to: "/components/something"}] and selected = "/components/something/better", ensure that items[1] is selected instead of items[0].

Put the Tabs indicator on the item having the longest `to` (or `id`)

---

README.md

There is no file named `smelte.css`. We nee to import `tailwind.css` that we just created in the step above it

Fixed file name in documentation to add smelte in an existing project

---

src/components/Icon/Icon.svelte
src/components/Tabs/TabButton.svelte
src/components/Tabs/Tabs.svelte

Issue: Missing color property for icon.
Suggestion: Add property `notselectedcolor`. Use case: if the tabs background is white, the tabs that are not selected will also have white text (it is hardcoded) and you cannot see the text. Would be nice if there was a `notselectedcolor` property for the tabs so you can customize the text color when a tab is not selected.
I have added a pull request for these two things! Have a nice day!

Fix color prop missing for icon, add not selected color for tabs

---

src/components/Card/Title.svelte
src/components/List/List.svelte
src/components/List/ListItem.svelte
src/components/RadioButton/RadioButton.svelte
src/components/Select/Select.svelte
src/components/Slider/Slider.svelte
src/components/Treeview/Treeview.svelte

I have updated svelte to the latest version ```3.16.7``` and I get some annoying compiler warnings ```unused export property 'PROPERTY_NAME'. If it is for external reference only, please consider using `export const 'PROPERTY_NAME'```.
I changed those properties from ```let``` to ```const``` to get rid of the warnings.

Fix compiler warnings

---

src/components/List/List.svelte
src/components/Select/Select.svelte

Two changes here:
1. Clicking the dropdown arrow on a `Select` control will toggle the list. Previously clicking the arrow did nothing.
2. Allow values such as `false` and `null` to be used as the id/value for Select items
Thanks!

Select control updates

---

src/components/Select/Select.svelte
src/components/TextField/TextField.svelte

This also sets `cursor-pointer` on the text field when autocomplete is disabled, so that it applies to the entire Select control.

When clicking the text field for a non-autocomplete Select, close the list

---

src/routes/components/_layout.svelte

Thanks for the great library! I'll be sure to use it in my next project.
I hid the navigation drawer from the demo.
After navigating to another page, there is no way to toggle the component menu back open without refreshing the page.
Let me know there is a preferred fix other than what I've got here - I'm brand new to Svelte :)

Sidenav cant be opened after leaving navigation drawers demo

---

src/components/Select/Select.svelte

Hello! I have found that after upgrading svelte(3.18.1 -> 3.19.1) my project is failing build
I have found, that from now on svelte disallows simultaneous use of attributes and shorthands.
https://github.com/sveltejs/svelte/commit/507661325629ca2b79df9d0103e47d5bd316f8e2
This pull request fixes it

upd(Select): removed simultaneous use of attribute and shorthand

---

src/components/Button/Button.svelte

Hi @matyunya , 
here is a refactor of small text and icon class attributes;  make small icon centered and small simple button text to fit button size

fix issue #83 Button small with icon

---

src/components/Select/Select.svelte

Updating `items` after creating the Select didn't work because `filteredItems` wasn't reactive to changes in `itemsProcessed`. This fixes that while retaining the filter ability.

Update Select when `items` changes after creation

---

src/components/Select/Select.svelte

Similar to the last one, except to make sure that `selectedLabel` updates when `items` changes. If selectedLabel is set as a prop on the component, it always uses the prop value.

Make selectedLabel reactive to changes in itemsProcessed

---

src/components/AppBar/AppBar.svelte

AppBar on docs site was butting against right side of the window due to `w-screen` with `fixed` position. 
Updated to use `w-full` to display header as intended.

Fix AppBar width

---

src/components/Tooltip/Tooltip.svelte

current hard coded delay of 500ms for the hideTootip is not making sense especially when multiple icons on appbar is having tooltip, this will lead to ugly multiple tootip showing up at appbar because user mouse move over a few icons in a row.
new changes export delayShow and delayHide and default it at 100ms, 100ms is pretty good. other devs might want to change to less than 100.

allow setting delay timing for show/hide tooltip

---

src/routes/components/progress-indicators.svelte

Docs are showing the wrong example - https://smeltejs.com/components/progress-indicators

Fix ProgressCircular import

---

src/components/Ripple/ripple.js

Based on other reference implementations (and general feel), the ripple should be triggered on `mousedown` and not `click` (~`mouseup`).
- Material Design Components
- https://material.io/develop/web/components/ripples
- https://material-components.github.io/material-components-web-catalog/#/component/ripple
- Material-UI (React)
- https://material-ui.com/components/buttons/#button
- svelte-mui
- https://svelte-mui.ibbf.ru/button
- https://svelte-mui.ibbf.ru/ripple
- https://github.com/vikignt/svelte-mui/blob/master/src/Ripple.svelte
- Angular Material
- https://material.angular.io/components/ripple/examples
`svelte-mui` also only triggers on [left click](https://github.com/vikignt/svelte-mui/blob/master/src/Ripple.svelte#L122-L127), but it seemed to be unique compared to the other …

Trigger ripple on mousedown instead of click (mouseup)

---

src/components/Button/variants.js
src/utils/css-extractor.js

Hi, three parts here:
- recursive crawl: Add the code of used smelte components to the purgeCss extractor. If the build performance is bad, there might be ways to improve it, since there are a bit too many recursions. I left a note in the code.
- add hardcoded whitelist. I tried several things, eg. updating the @fullhuman/postcss-purgecss to newer version 2.3.0, but nothing seemed to make whitelisting work. So, I've put the classes in the extractor. It is workaround, rather than  a fix. 
- update button hover variants. The hover:... classes were purged away, so I've explicitly added them for button. I did not check other components, they may have the same problem.
Should fix: #115, #110, #97, #91 
Could fix: #155

Fix production build

---

src/components/Slider/Slider.svelte

getComputeStyle is not existent at server-side and that causes the HTTP 500 error. Using CSS var fixes the error.
By the way, thanks for smelte, it's really cool !!

Using CSS vars for getting color

---

src/utils/color.js

**What ?**
An optional feature to support color definitions like `var(--color-blue)` while current colors like `#b027b0` are still also working
**How ?**
At tailwind.config.js you can now add a color definition like `primary: "var(--color-blue)"` or normal ones like `primary: "#b027b0"`
**Who?**
This feature is requested by @matt-psaltis at https://github.com/matyunya/smelte/issues/147
Thank you very much for smelte !!

Adding support for color var

---

examples/buttons.txt
examples/card.txt
examples/checkboxes.txt
examples/chip-outlined.txt
examples/chip.txt
examples/custom-lists.txt
examples/date-pickers.txt
examples/dialog.txt
examples/images.txt
examples/lists.txt
examples/menus.txt
examples/navigation-drawers.txt
examples/progress-indicators.txt
examples/selects.txt
examples/sliders.txt
examples/snackbars.txt
examples/table.txt
examples/tabs-with-content.txt
examples/tabs.txt
examples/text-fields.txt
examples/treeview.txt

**What?**
A simple commit to fix a couple of syntax errors at the **examples** (especially the imports and some references to docs/Code)
**Why?**
To ease the use of Smelte for newcomers (i.e.: I was driving crazy debugging the date picker until I realize the correct value is `i.detail` and not just `i` at the change event)
**How?**
I just copied and pasted the examples in a running Smelte 1.0.15 and try to run them. Then fix a minor error here and a minor error there comparing with the real code.
Thank you for Smelte, it's really cool !!

Minor examples syntax error fixes

---

src/components/NavigationDrawer/NavigationDrawer.svelte

Creating a NavigationDrawer component with the `show` property set to `false`, it wasn't hiding the drawer on larger screens. It was being overriden by this line:
```
$: persistent = show = $bp !== "sm";
```
I've added a variable called `hidden`, set to the original `show` value set. Only if it's false do we run the check above.

Fix for NavigationDrawer not hiding with when expected

---

src/breakpoints.js

It's probably only come to light because I'm using Svelte Router SPA but the changing paths looking to be calling OnDestroy in breakpoints.js. It was just incorrect wording and the missing listener name.

Fix for destroying event listener in breakpoints.js

---

package.json

The types only work if svelte-typed-component is also installed. I thought previously, that dev-dependencies would also be pulled, but it does not seem to be the case.

Move svelte-typed-component to dependencies

---

src/components/Slider/Slider.svelte

The `value` incorrectly treated as percents for calculating slider gradients.
I fixed this by converting it from min..max range to 0..100.

Fixed slider gradient for different value ranges

---

src/components/Icon/Icon.svelte

Make icons **unselectable** by default.
This will prevent undesirable behavior like this:
By making icons unselectable:
This will also prevent weird copy/past when element contain an icon. For example, if we copy/paste the first checkbox of the screenshot:
- With user selectable icons:
`check_box_outline_blank A checkbox`
- With non user selectable icons:
`A checkbox`

Unselectable icon by default

---

src/components/DatePicker/Picker.svelte

When having the picker open, it highlights the current day. It also highlighted the current day in other years as well.
The value 'isToday' suggests that it should only highlight the 'today' value, and not the same dates in other years as well.
This PR fixes #202.

fix: check whether today is in the same year

---

src/components/Button/Button.svelte

Fixes #204 
When adding a button inside a form, the button type is by default 'empty' (for instance for the date picker). Having it default to `type="button"` the next and previous buttons will not trigger a form submit.

Add a default type to the button.

---

README.md
src/routes/index.svelte

This adds clarification for where to put the rollup plugin
closes #210

docs: suggest placement of rollup plugin

---

src/components/DatePicker/DatePicker.svelte

1. Clicking in the DatePicker's TextField opens the DatePicker. I know this isn't default behaviour in the Material UI library but I think it's a good stopgap until manually entering dates is better supported.
2. Once a date has been selected, users can edit the date and it'll be valid, providing its format matches DD/MM/YYYY or YYYY/MM/DD.

Improving support for manually entered dates

---

src/components/DataTable/DataTable.svelte
src/components/DataTable/Header.svelte
src/components/DataTable/Pagination.svelte

These changes allow server-side sorting.
`customSort` tells the table to not do client side sort and slice.
`showSort` tells the table to show the sort icon on the column that is currently sorted.

Data table - Allow server side sorting.  Show sort icon on column that is sorted.

---

package.json
src/index.d.ts
src/notification-queue.d.ts

When `smelte` is used with `typescript`, the compiler is confused because the file `src/index.d.ts` isn't part of the package. Adding them to the bundle fixes that problem. `svelte-typed-component` is imported from those file definitions. Moving that dependency from `devDependencies` to `dependencies` fixes that import.
I didn't find any contribution guidelines, let me know if that's the right way of helping :wink: Also, well done for your good work :clap: 
Closes #166, closes #109

Expose type definition files

---

src/components/TextField/TextField.svelte

Fixed an issue causing the color of the underline to not change properly with the color attribute of TextField
I noticed an issue while working on a side project that the Underline does not have the `color` prop passed down to it from the TextField so I added that prop in.

Fix TextField Underline color mismatch issue

---

src/components/Tabs/Tab.d.ts
src/components/Tabs/Tab.svelte

This matches how it's used in the `#if` block and defaults to not matching (`undefined !== null`).
Excerpt from the web guide that uses it as well:
```svelte
<Tabs
selected="1"
class="bg-black shadow-sm mt-6 text-white rounded-t-lg"
color="yellow-a200"
let:selected={selected}
{loading}
items={[
{ id: "1", text: 'Cats', icon: 'alarm_on' },
{ id: "2", text: 'Kittens', icon: 'bug_report' },
{ id: "3", text: 'Kitties', icon: 'eject' },
]}>
<div
slot="content"
class="flex items-center content-center overflow-hidden w-full bg-gray-900 h-full"
style="height: 250px"
>
<Tab id="1" {selected}>
<Image
alt="kitten 1"
class="w-full"
src="https://placekitten.com/400/250"
width="400"
height="250"
/>
</Tab>
```
Where the `selected` variable is the items' `id`.

Correct Tab.selected prop to match usage

---

src/components/List/List.svelte

This allows using the `items` (plural) slot to make this function more like a plain `ul` with the proper list classes (not that they're lengthy, but more for consistency).

Add items slot to list to override all items

---

src/components/List/List.d.ts

Changes the `item` prop type to `ListItemBase` instead of `{}`, and adds the new `items` slot introduced in #258.

Fix List slot typings
